      DOUBLE PRECISION FUNCTION CUMPHI(X)
C ======================================================================
C     FUNCTION TO CALCULATE THE INTEGRAL OF THE CUMULATIVE
C     PROBABILITY DENSITY FUNCTION FOR THE NORMAL DISTRIBUTION
C     FROM MINUS INFINITY TO X.  ROUTINE USES APPROXIMATION GIVEN
C     GIVEN IN SECTION 26.2.19 OF FOLLOWING REFERENCE.
C     THE ERROR IN THE APPROXIMATION IS LESS THAN 1.5E-7.
C
C     REFERENCE: ABRAMOWITZ, MILTON, AND STEGUN, I. A., 1964, HANDBOOK
C                OF MATHEMATICAL FUNCTIONS: U.S. DEPARTMENT OF COMMERCE,
C                NATIONAL BUREAU OF STANDARDS, APPLIED MATHEMATICS
C                SERIES 55, P. 932.
C ----------------------------------------------------------------------
C     INITIAL CODING:  JULY 1991
C     WRITTEN BY:      CHARLES G. CRAWFORD
C                      U.S. GEOLOGICAL SURVEY, WRD
C                      INDIANAPOLIS, INDIANA
C ----------------------------------------------------------------------
C     VARIABLES
C -------------
C     X        DOUBLE PRECISION   UPPER LIMIT OF INTEGRAL
C     D1       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     D2       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     D3       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     D4       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     D5       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     D6       DOUBLE PRECISION   CONSTANT USED IN APPROXIMATION
C     CUMPHI   DOUBLE PRECISION   INTEGRAL OF CDF
C ----------------------------------------------------------------------
C     DECLARE VARIABLES
C ---------------------
      DOUBLE PRECISION D1,D2,D3,D4,D5,D6,X
      PARAMETER (D1=0.0498673470D0,D2=0.0211410061D0,D3=0.0032776263D0)
      PARAMETER (D4=0.0000380036D0,D5=0.0000488906D0,D6=0.0000053830D0)
C ----------------------------------------------------------------------
C
      CUMPHI=1.0D0-0.5D0*
     2 ((((((D6*X+D5)*X+D4)*X+D3)*X+D2)*X+D1)*X+1.0D0)**(-16)
C
C     RETURN TO CALLING PROGRAM
C
      RETURN
      END
